spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/web_store_test?useSSL=false
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

    show-sql: true

  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: senkoShop@outlook.com
    password: Midostar10035
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8084

